### ISSUE TITLE
Conflicts with react-mixin

### ISSUE THREAD

**Issue by dallonf** [gaearon/react-proxy#22]
When reloading a component decorated with the [react-mixin](https://github.com/brigand/react-mixin) decorator, it appears that it will attempt to apply the mixin again, throwing a `cannot merge returns because both have the "locales" key` error, for example, if `locales` is defined in `contextTypes` on the mixin.

I suspect this is because `react-mixin` mutates the class in-place rather than wrapping or copying. I'm not sure there is a sane solution to this, but definitely something to think about.

**Comment by gaearon** [comment]
Fair. This isn't really something we can fix on our side—React Mixin can either choose to avoid mutation, or to set a flag for early exits with double-wrapping.

Also, you probably [shouldn't be using mixins in the first place](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750). It's really easy to avoid them, and strategies like higher order components tend to scale better without complicating codebases or introducing issues like this one.
