### ISSUE TITLE
ProxyClass prevents filtering on displayName

### ISSUE THREAD

**Issue by Agowan** [gaearon/react-proxy#26]
Hi,
I have a question how do go further in this matter. Essentially we are using react-hot-loder, but I found that in the end it's this library that causes my problem.

Worth mentioning is that this might be an anti pattern but I can't find a better way to do this atm.

In a component we are filtering children based on the displayName to render the results in multiple places.
```jsx
render() {
  let actions = this.props.children.filter(c => c.type.displayName.indexOf("action") > -1);
  let columns = this.props.children.filter(c => c.type.displayName.indexOf("column") > -1);
  return (<div>
    {actions}
    <table>
    <head>
      <tr>{columns}</tr>
    </thead>
    {...}
  </div>);
}
```
The problem is that we can't access the displayName due `this.props.children` contains instances of `ProxyClass` and where `.type.displayName` return `undefined`.

May I ask for som guidance here, is there a better way to solve this or is there a way to access the actual child through the proxy class?

Regards Niklas

**Comment by gaearon** [comment]
While displayName shouldn't get lost (please show a reproducible project showing how that happens), you really shouldn't rely on it in your code.

Instead, pass `actions` and `columns` as separate props and don't use `children`.

**Comment by Agowan** [comment]
I will of course do as you suggested pass them as children in the future, good point there. 

But for the sake of solving the problem I have managed to reproduce the problem:
https://github.com/davezuko/react-redux-starter-kit/tree/no-server

I also managed to narrow the problem a bit.
When using:
```jsx
export class Greeting extends React.Component { 
   ...
}
```
The the `displayName` does return the correct name.

But when using:
```jsx
export default React.createClass({
  ...
});
```
The `displayName` is then undefined.

The class name is not present in the later case, so I suppose that the `InitialClass` won't be set (https://github.com/gaearon/react-proxy/blob/master/src/createClassProxy.js#L17).

This might be my lacking knowledge about how export works in javascript that prevented me from seeing the problem at start.
Is it so that this is by design?

**Comment by gaearon** [comment]
From https://github.com/gaearon/babel-plugin-react-transform/blob/master/README.md#limitations:

>When using React.createClass() and allowing babel to extract the displayName property you must ensure that `babel-plugin-react-display-name` is included before `react-transform`.
