### ISSUE TITLE
element.type.displayName differs from the original component (is undefined)

### ISSUE THREAD

**Issue by technicallyfeasible** [gaearon/react-proxy#30]
The proxy should have the same displayName like the original component to allow for type checking.

**Comment by technicallyfeasible** [comment]
I just noticed the problem appears only if React.createClass is used instead .of class MyClass extends React.Component.
Also, explicitly specifying displayName in the object given to React.createClass solves this problem. Would be good though if the implicitly retrieved name worked as well.

This works without proxy (type.displayName === 'SurfaceBody') but not with proxy:

	const SurfaceBody = React.createClass({
	});
	export default SurfaceBody;

This works with proxy (type.displayName === 'SurfaceBody')

	const SurfaceBody = React.createClass({
	  displayName: 'SurfaceBody',
	});
	export default SurfaceBody;

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-proxy/issues/26#issuecomment-142546013
