### ISSUE TITLE
Undefined method in __reactAutoBindMap

### ISSUE THREAD

**Issue by technicallyfeasible** [gaearon/react-proxy#33]
I have a problem with one of our projects that uses hot reloading with webpackand thus react-proxy.

I get an error "Uncaught TypeError: Cannot read property 'bind' of undefined". The reason this happens is because __reactAutoBindMap has all values undefined after being wrapped in the proxy. The specific class inherits another class which also has a mixin and I suspect that this might be a specific constellation. As far as I can see, there are two probable causes for the issue:

1. createPrototypeProxy has "const currentNames = Object.getOwnPropertyNames(current);", which only picks up own properties and copies them to the proxy.
2. Because of 1., the following snippet then assigns "undefined" to all properties in the original __reactAutoBindMap (from createPrototypeProxy.createAutoBindMap):

	let __reactAutoBindMap = {};
	for (let name in current.__reactAutoBindMap) {
		if (current.__reactAutoBindMap.hasOwnProperty(name)) {
			__reactAutoBindMap[name] = proxy[name];
		}
	}

This happens because proxy now does not have all of the inherited methods.

I can fix the problem by replacing the second fragment with

	let __reactAutoBindMap = {};
	for (let name in current.__reactAutoBindMap) {
		if (proxy.hasOwnProperty(name)) {
			__reactAutoBindMap[name] = proxy[name];
		}
	}

but I am not sure if that does not break something else since I have not completely understood the implications of this code.

Can you shed some light on this please?

**Comment by gaearon** [comment]
You can try making you change and seeing if the tests pass. :-)

Generally inheritance is very bad idea in React, and twice so when you mix it with `createClass`.
Even React team doesn't officially support this use case.

**Comment by technicallyfeasible** [comment]
Tests pass in this pull request:
https://github.com/gaearon/react-proxy/pull/35

**Comment by technicallyfeasible** [comment]
The problem actually occurs when using a third party component and there is nothing I can do to change the code.

**Comment by gaearon** [comment]
Thanks for the PR! I'll review soon.

>The problem actually occurs when using a third party component and there is nothing I can do to change the code.

Curious—how come a third party component is wrapped in a proxy?

**Comment by technicallyfeasible** [comment]
It is because it was transformed by react-transform-hmr for hot reloading. I have excluded it from hot reloading for now though.

**Comment by technicallyfeasible** [comment]
It's also more of a file that has to patch some things in a third party component and inherit from it to do that. The component itself is in node_modules and excluded automatically.

**Comment by gaearon** [comment]
>It's also more of a file that has to patch some things in a third party component and inherit from it to do that. 

That's exactly why I say inheritance is a bad practice in React. You should not inherit third-party components.

**Comment by gaearon** [comment]
I merged #35 so that should be solved.

**Comment by gaearon** [comment]
Note that React Proxy 2.x isn't yet used in React Transform HMR so it'll take some time to get available directly.

**Comment by technicallyfeasible** [comment]
Thanks. I managed to find a workaround so I don't need this immediately but it's good that it's there.

**Comment by gaearon** [comment]
Cool! FWIW I backported it to 1.x too.
