### ISSUE TITLE
Cannot proxy classes without transpiling them

### ISSUE THREAD

**Issue by akorchev** [gaearon/react-proxy#41]
Currently it throws `Class constructors cannot be invoked without 'new'`. I [forked](https://github.com/akorchev/react-proxy/commit/0b962f4cde28c14addb4e0773f54f4d689c8ad74) the project to show the problem. Unfortunately I failed to find a fix. The implementation relies a lot on "classic" prototype inheritance and instantiating objects with `CurrentComponent.apply(this, arguments)`. The best I could get was instantiating a `CurrentComponent` and copying its properties to `this`:

```
 ProxyComponent = function () {
    const current = new CurrentComponent(...arguments);

    Object.getOwnPropertyNames(current).forEach(property => {
      if (RESERVED_STATICS.indexOf(property) > -1) {
        return;
      }
      if (typeof current[property] !== 'function') {
        this[property] = current[property];
      }
    });
  };
```

Then only 7 tests failed. Still not a fix though.

**Comment by gaearon** [comment]
Would invoking it with `new` all the time work?

**Comment by akorchev** [comment]
Nope. Would an implementation based on inheritance work? I mean `extends` not __proto__ setting.

**Comment by gaearon** [comment]
I don’t have a deep knowledge of ES6 classes but I still don’t see why they you’d *have* to use `extends`. Can you please clarify what happens if you change the code to call `return new CurrentComponent(...arguments)`?

**Comment by akorchev** [comment]
This was the first thing I tried :) - 81 tests fail. But it is expected because the code relies on `CurrentComponent.apply(this, arguments)` to set set all constructor properties of CurrentComponent to ProxyComponent. Kind of calling a different constructor with your context.

**Comment by akorchev** [comment]
[Got](https://github.com/akorchev/react-proxy/commit/70f12cc3d232805b0c27601faad81f5388769fdc) it to one failing [test](https://github.com/akorchev/react-proxy/blob/master/test/consistency.js#L226). For the life of me can't make it pass. For some reason instantiating the class with new fails only for this test.

**Comment by gaearon** [comment]
This test is intended to be there for checking environments where dynamic code evaluation is forbidden. This is for the "else" case where rather than generate a function, we use an existing one (but it has a generic name).

In fact I think the dynamic evaluation might be unnecessary. It is there cause I couldn't figure out how to change function name dynamically. But I read somewhere that while assignment doesn't work, you can use Object.defineProperty. Maybe we can try that instead, and then fix that single code path.

**Comment by akorchev** [comment]
I've [managed](https://github.com/akorchev/react-proxy/commit/c271cc46426eb9ccf81b8c1b99cb4e415ee126b7) to get it to work after all. For some reason using object spread for the constructor parameters ended up with 'cannot call method apply of undefined'. Here is the pull request: https://github.com/gaearon/react-proxy/pull/42

**Comment by gaearon** [comment]
Out in 1.1.3 (2.0.2 too although nobody uses 2.x yet probably).
