### ISSUE TITLE
Uglify borked on 1.1.4

### ISSUE THREAD

**Issue by airlanggacahya** [gaearon/react-proxy#48]
Uglify borked with error message:
```
> webpack --config webpack.config.prod.js

Hash: df87c9f1484ead5c19e1
Version: webpack 1.12.14
Time: 5804ms
                             Asset    Size  Chunks             Chunk Names
    bundle.df87c9f1484ead5c19e1.js  777 kB       0  [emitted]  main
bundle.df87c9f1484ead5c19e1.js.map  938 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 269 hidden modules

ERROR in bundle.df87c9f1484ead5c19e1.js from UglifyJs
Unexpected token name «key», expected punc «;» [./~/react-proxy/modules/createClassProxy.js:45,0]
```

Configuration: https://gist.github.com/airlanggacahya/cc8e1c68e9212221f3ad

**Comment by airlanggacahya** [comment]
Description updated.

Rolling back package to 1.1.2 fixed it.

**Comment by gaearon** [comment]
Yeah, looks like we left out `let`/`const` transpilation by mistake when tweaking configs.
cc @akorchev

**Comment by gaearon** [comment]
That said there is absolutely no reason why you’d ever want to uglify React Proxy.
It should **never** be used in produciton.

**Comment by airlanggacahya** [comment]
@gaearon whoops, right now I'm tinkering with package.json to work on windows and linux. Somehow my mistake made webpack uglify all dev dependencies code.

**Comment by akorchev** [comment]
I will bring let / const transpilation back. I trust tests too much.

**Comment by gaearon** [comment]
@akorchev No prob, I’m on it, will push a fix soon

**Comment by gaearon** [comment]
Should be fixed in 1.1.6.

**Comment by gaearon** [comment]
(And we definitely need better.. integration tests?)

**Comment by akorchev** [comment]
Running the tests in a few browsers should be OK I guess?. BrowserStack? SauceLabs?

**Comment by gaearon** [comment]
BrowserStack could work, I can ask them for a license.
