### ISSUE TITLE
Fails on IE11 Win10 (no Array.prototype.find)

### ISSUE THREAD

**Issue by gnarf** [gaearon/react-proxy#52]
https://github.com/gaearon/react-proxy/blob/2d79a5bee47113215a1cb5e3ad0a0297d88ccf78/src/createClassProxy.js#L35

This line is calling `[].find` which doesn't exist in IE11.

<img width="435" alt="screenshot 2016-03-09 15 37 05" src="https://cloud.githubusercontent.com/assets/549355/13649701/e501fbe8-e60c-11e5-816a-1bd5280d6593.png">
<img width="401" alt="screenshot 2016-03-09 15 37 21" src="https://cloud.githubusercontent.com/assets/549355/13649702/e6d1ccf0-e60c-11e5-90a5-3a60e35995a0.png">

**Comment by Restuta** [comment]
same issue

**Comment by gaearon** [comment]
Thanks! Fix is out in 1.1.8.
